### ISSUE TITLE
Making the data enterer dashboard fully functional

### ISSUE THREAD

**Issue by wedahafiz** [NBenawa/Archive-MIS#4]

**Comment by NBenawa** [comment]
working on the data enterer interface

**Comment by NBenawa** [comment]
completed work on data enterer interface

**Comment by ghezalahmad** [comment]
Dear Najib,
You should present your system to the minister's office this week, but according to your system's milestone, it seems, there is not that much complexity, therefore, I am requesting you if you can speed up your work to join the next project instead of this.

Looking forward to hear from you.
